### ISSUE TITLE
Which branch should I use in my project?

### ISSUE THREAD

**Issue by MewX** [lightningkite/kotlin-anko-observable#2]
I'm really excited to try this library, so, which branch should I use?
Thx!

**Comment by UnknownJoe796** [comment]
Hi! Sorry for the delay, I just saw this - take a look at the starter project (https://github.com/UnknownJoe796/kotlin-components-starter). It's the best reference. Use the master branch for now - we rarely make breaking changes but we do add new functionality regularly. If you have any problems getting it running let me know! I'm glad to help.
